apiVersion: 1

datasources:
  - name: birds-db
    type: frser-sqlite-datasource
    uid: birds-db
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /var/lib/bird-feeder/birds.db
      pathPrefix: ""
      attachList: []
