#!/bin/sh
set -e

VIDEO_FILE="${VIDEO_FILE:-/videos/sample.mp4}"
FPS="${FPS:-}"
STREAM_NAME="${STREAM_NAME:-stream}"

# Build the ffmpeg command
if [ -n "$FPS" ]; then
    # Re-encode to force a specific frame rate
    FFMPEG_CMD="ffmpeg -re -stream_loop -1 -i ${VIDEO_FILE} -vf fps=${FPS} -c:v libx264 -preset ultrafast -tune zerolatency -g ${FPS} -an -f rtsp -rtsp_transport tcp rtsp://localhost:\$RTSP_PORT/\$MTX_PATH"
else
    # Pass through at native frame rate (no re-encoding)
    FFMPEG_CMD="ffmpeg -re -stream_loop -1 -i ${VIDEO_FILE} -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:\$RTSP_PORT/\$MTX_PATH"
fi

echo "=== Virtual RTSP Server ==="
echo "  Video:  ${VIDEO_FILE}"
echo "  FPS:    ${FPS:-native}"
echo "  Stream: rtsp://localhost:8554/${STREAM_NAME}"
echo "=========================="

# Generate mediamtx.yml from template
cat > /mediamtx.yml <<EOF
# Auto-generated by entrypoint.sh

rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
webrtcAddress: :8889

paths:
  ${STREAM_NAME}:
    runOnInit: >-
      ${FFMPEG_CMD}
    runOnInitRestart: yes
EOF

exec /mediamtx /mediamtx.yml
